name: Generate Oli TV EPG

on:
  schedule:
    - cron: '0 */4 * * *' 
  push:
    branches:
      - main  # Runs on push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Run script
        run: |
          curl -o ./epg/olitv.xml "https://olidigital.space/olitv-epg.php"
          gzip -kf ./epg/olitv.xml

      - name: Commit changes if any
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Schedule auto-updated on $(date -u '+%Y-%m-%d %H:%M:%S UTC')"

      - name: Pull latest changes from remote
        run: git pull origin main --rebase

      - name: Push changes
        run: git push origin main
